/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@class NSHashTable, NSMutableSet, SBApplication, SBChevronView, SBControlCenterRootView, SBControlCenterViewController, SBControlCenterWindow, UIView, _UIBackdropView;

@interface SBControlCenterController : UIViewController /*<SBControlCenterViewControllerDelegate>*/
{
    SBControlCenterWindow *_window;
    SBControlCenterRootView *_rootView;
    SBControlCenterViewController *_viewController;
    UIView *_fullScreenGrabberContainer;
    _UIBackdropView *_fullScreenGrabberBackdrop;
    SBChevronView *_fullScreenChevron;
    NSMutableSet *_preventDismissalOnLockReasons;
    BOOL _uiLocked;
    NSHashTable *_observers;
    long long _orientation;
    BOOL _animatingInitialPresentation;
    BOOL _gotFirstBackdropUpdate;
    BOOL _inGrabberOnlyMode;
    BOOL _presented;
    BOOL _transitioning;
    BOOL _fullyRevealed;
    SBApplication *_coveredApplication;
}

+ (void)notifyControlCenterControl:(id)arg1 didActivate:(BOOL)arg2;
+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreatingIfNeeded:(BOOL)arg1;
@property(nonatomic, getter=isFullyRevealed) BOOL fullyRevealed; // @synthesize fullyRevealed=_fullyRevealed;
@property(nonatomic, getter=isTransitioning) BOOL transitioning; // @synthesize transitioning=_transitioning;
@property(nonatomic, getter=isPresented) BOOL presented; // @synthesize presented=_presented;
@property(retain, nonatomic) SBApplication *coveredApplication; // @synthesize coveredApplication=_coveredApplication;
@property(nonatomic) BOOL inGrabberOnlyMode; // @synthesize inGrabberOnlyMode=_inGrabberOnlyMode;
@property(nonatomic, getter=isUILocked) BOOL UILocked; // @synthesize UILocked=_uiLocked;
- (void)controlCenterViewController:(id)arg1 backdropViewDidUpdate:(id)arg2;
- (void)controlCenterViewController:(id)arg1 handlePan:(id)arg2;
- (void)controlCenterViewController:(id)arg1 handleTap:(id)arg2;
- (BOOL)controlCenterViewController:(id)arg1 canHandleGestureRecognizer:(id)arg2;
- (void)controlCenterViewControllerWantsDismissal:(id)arg1;
- (void)_finishPresenting:(BOOL)arg1 completion:(id)arg2;
- (void)_dismissWithDuration:(double)arg1 additionalAnimations:(id)arg2 completion:(void)arg3;
- (void)dismissAnimated:(BOOL)arg1 withAdditionalAnimations:(id)arg2 completion:(void)arg3;
- (void)dismissAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)dismissAnimated:(BOOL)arg1;
- (void)_presentWithDuration:(double)arg1 completion:(id)arg2;
- (void)presentAnimated:(BOOL)arg1;
- (void)presentAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)hideGrabberAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)hideGrabberAnimated:(BOOL)arg1;
- (void)showGrabberAnimated:(BOOL)arg1;
- (void)cancelTransition;
- (void)endTransitionWithVelocity:(struct CGPoint)arg1 completion:(id)arg2;
- (id)_createDynamicAnimationForShow:(BOOL)arg1 currentValue:(double)arg2 velocity:(double)arg3;
- (void)updateTransitionWithTouchLocation:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
- (void)beginTransitionWithTouchLocation:(struct CGPoint)arg1;
- (void)_endPresentation;
- (void)_beginPresentation;
- (BOOL)allowHideTransition;
- (BOOL)allowShowTransition;
- (BOOL)_allowsShowTransition;
- (void)_setNCGrabberHidden:(BOOL)arg1;
- (void)_updateGrabberVisibility;
- (void)_updateRevealPercentage:(double)arg1;
- (void)_revealSlidingViewToHeight:(double)arg1;
- (double)_controlCenterHeightForTouchLocation:(struct CGPoint)arg1;
- (double)_yValueForClosed;
- (double)_yValueForOpen;
- (BOOL)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (BOOL)wantsFullScreenLayout;
- (id)_window;
- (void)preventDismissalOnLock:(BOOL)arg1 forReason:(id)arg2;
- (void)_dismissOnLock;
- (void)_uiRelockedNotification:(id)arg1;
- (void)_lockStateChangedNotification:(id)arg1;
- (BOOL)isGrabberVisible;
- (BOOL)isVisible;
- (void)loadView;
- (BOOL)handleMenuButtonTap;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)_enumerateObservers:(id)arg1;
- (BOOL)isAvailableWhileLocked;
- (void)dealloc;
- (id)init;

@end

