/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#import "SBControlCenterSectionViewControllerDelegate-Protocol.h"

@interface SBControlCenterSectionViewController : UIViewController

+ (Class)viewClass;

@property (nonatomic, assign) id <SBControlCenterSectionViewControllerDelegate> delegate;

- (void)controlCenterDidFinishTransition;
- (void)controlCenterWillBeginTransition;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)noteSettingsDidUpdate:(id)arg1;

- (CGSize)contentSizeForOrientation:(UIInterfaceOrientation)arg1;
- (BOOL)enabledForOrientation:(UIInterfaceOrientation)arg1;

@property (readonly, nonatomic) NSString *sectionIdentifier;

@end

