/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#import "BBWeeAppControllerHost-Protocol.h"

@protocol BBWeeAppController <NSObject>
- (UIView *)view;

@optional

@property (nonatomic, assign) id <BBWeeAppControllerHost> host;

- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)setPresentationView:(id)arg1;
- (float)presentationHeight;
- (void)unloadPresentationController;
- (id)presentationControllerForMode:(int)arg1;
- (id)launchURLForTapLocation:(CGPoint)arg1;
- (id)launchURL;
- (void)loadView;
- (void)clearShapshotImage;
- (void)unloadView;
- (void)loadFullView;
- (void)loadPlaceholderView;
- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(UIInterfaceOrientation)arg1;
- (void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)arg1;
- (void)viewDidDisappear;
- (void)viewWillAppear;
- (CGFloat)viewHeight;

@end

